
import Nav from "@/components/root component/Nav";
import "./globals.css";

import Footer from "@/components/root component/Footer";
import Providers from "@/components/Providers";
import { Toaster } from "sonner";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, session }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers session={session}>
          <Nav />
          <main className="w-11/12 mx-auto min-h-screen pt-20">{children}</main>
          <Footer />
          <Toaster position="top-right" richColors />
        </Providers>
      </body>
    </html>
  );
}
